# Generated by Django 6.0.3 on 2026-03-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='selling_pric',
            new_name='selling_price',
        ),
    ]
