# Generated by Django 6.0.3 on 2026-03-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_selling_pric_purchaseitem_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='batch_nnumber',
            new_name='batch_number',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='expirey_date',
            new_name='expiry_date',
        ),
    ]
