# Generated by Django 6.0.3 on 2026-03-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0006_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.batch'),
        ),
    ]
