# Generated by Django 6.0.3 on 2026-04-03 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_price_remove_cartitem_sub_total'),
        ('orders', '0006_order_orders_orde_user_id_a87c6f_idx_and_more'),
        ('stores', '0002_store_address_store_city_store_closed_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('WEBHOOK_RECEIVED', 'Webhook Received'), ('RETRY', 'Retry')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='uniq_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('razorpay_payment_id',), name='uniq_payment'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['payment', 'event'], name='orders_paym_payment_991f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['created_at'], name='orders_paym_created_7e8ccf_idx'),
        ),
    ]
