# Generated by Django 6.0.3 on 2026-03-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
