# Generated by Django 6.0.3 on 2026-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_inventorylog'),
        ('stores', '0002_store_address_store_city_store_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'store', 'expiry_date'], name='products_ba_product_02876a_idx'),
        ),
    ]
