"""
Django settings for retyn project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import sentry_sdk
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kys)qrloqlg@yolut!sqklhpmymf$q1ev0+&x&9i1xu3(2dbx)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"
SECRET_KEY = os.getenv("SECRET_KEY")
ALLOWED_HOSTS = ["*"]

# ALLOWED_HOSTS = [
#     'nontraceably-proauthor-selena.ngrok-free.dev', 
#     'localhost', 
#     '127.0.0.1',
#     '.ngrok-free.app', # This covers any ngrok-free.app subdomains
#     '.ngrok-free.dev', # This covers your current .dev subdomain
# ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'stores',
    'products',
    'offers', 
    'carts',
    'orders',
    'suppliers',
    'purchases',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'retyn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'retyn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.User'

RAZORPAY_KEY_ID = 'rzp_test_SXRr37tLjnTA8c'
RAZORPAY_KEY_SECRET = 'B6Xe7UsbYyoBywI0XcZ8vYTB'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

DEFAULT_PERMISSION_CLASSES = [
    'rest_framework.permissions.IsAuthenticated'
]

LOGGING = {
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'simple':{
            'format' : '%{levelname}s %{message}s',
        } 
    },
    'handlers':{
        'console':{
            'class':'logging.StreamHandler',
            'formatter':'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/app/logs.django.log',
            'formatter':'simple',
        },
    },
    'root':{
        'handlers':['console'],
        'level':'INFO',
    },
}

#Redis 
REDIS_URL = 'redis://127.0.0.1:6379/0'
#Celery Config
CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
#Result backend
CELERY_RESULT_BACKEND = REDIS_URL
#Timezone
CELERY_TIMEZONE = 'Asia/Kolkata'


CACHES = {
    'default':{
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':os.getenv("REDIS_URL"),
        'OPTIONS':{
            'CLIENT_CLASS':'django_redis.client.DefaultClient',
        }
    }
}

CELERY_BEAT_SCHEDULE = {
    "retry-failed-payments": {
        "task": "orders.tasks.retry_failed_payments",
        "schedule": 300.0,
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://nontraceably-proauthor-selena.ngrok-free.dev',
]

RAZORPAY_WEBHOOK_SECRET = "Asustuf3!"

sentry_sdk.init(
    dsn="",
    traces_sample_rate = 0.2
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')