# Generated by Django 6.0.3 on 2026-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='max_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
